Key: 
Token: 
BoardId: 

# Describe the workflow. Each step can be mapped to either a single JIRA
# status, or a list of statuses that will be treated as equivalent
Workflow:
    Backlog: 
        - Backlog
    Planning:
        - Planning
    Analysis:
        - Analysis
    Testing:
        - Configuration/Unit Testing
    Data Conversion:
        - Data Conversion
    Functional Testing:
        - Functional Testing
        - Parallel Test
    Production:
        - Production
    Transition: 
        - Transition
    Done:
        - Done
        - CLOSED_IN_TRELLO_INTERNAL_SYSTEM
